### ISSUE TITLE
Perhaps a mistake in RuneCount()

### ISSUE THREAD

**Issue by zhangyuwu** [migueldeicaza/NStack#21]
public static int RuneCount(byte[] buffer, int offset = 0, int count = -1)
        {
            if (buffer == null)
                throw new ArgumentNullException(nameof(buffer));
            if (count == -1)
                count = buffer.Length;
            int n = 0;
            for (int i = offset; i < count;) {    <<---- the loop should be from 0 to count, obviously it won't work if offset is greater than count.
                n++;
                var c = buffer[i];
                ......
            }
        }

**Comment by migueldeicaza** [comment]
The purpose of offset is to start counting at the specified offset in the buffer, that is why it is not zero.
