### ISSUE TITLE
NuGet brings in Standard Dependencies :(

### ISSUE THREAD

**Issue by jamesmontemagno** [migueldeicaza/NStack#5]
From my understanding you have to list each platform and what it actually need: https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers.nuspec#L18-L46

Is what I do. Else installing your library does something like this:
![image](https://cloud.githubusercontent.com/assets/1676321/26748651/57aed1ac-47b4-11e7-85cf-32ea018ba0ac.png)

Resulting in: 
![image](https://cloud.githubusercontent.com/assets/1676321/26748658/777cc502-47b4-11e7-8d6d-cb6119e6a63b.png)

This was just into a xamarin android app. Perhaps I am doing something wrong or misunderstanding the changes they made.

**Comment by migueldeicaza** [comment]
Mhm I am using nugetizer;  I dont actually have a nuspec file.   But the above looks hideous indeed.

If I have to, I will add a manual nuspec to solve this

**Comment by onovotny** [comment]
Those should all be hidden from you if you use PackageReference. The optimization James has is useful for minimizing pain of packages.config users.

Also, once netstandard2 is a thing, if the Xamarin packages reference (implicitly) netstandard.library 2.0, then all of those dependencies won't even be brought in since netstandard.library 2.0 doesn't have those dependencies. instead, it's all in the single package.

**Comment by onovotny** [comment]
This will work even if the class library has a reference to netstandard.library 1.6.1 since the Xamarin project's netstandard.library 2.0 library will "win". the whole dependency graph gets short circuited and simplified.

**Comment by migueldeicaza** [comment]
But how would our users know that they need to use PackageReference?

For now, I went with a manual nuspec file that does what James describes and now it looks clean.   Hopefully @kzu will know how to add this to NuGetizer

**Comment by migueldeicaza** [comment]
The new nuGet package 0.2.0 shoudl work.

**Comment by jamesmontemagno** [comment]
Would system.valuetuple needed to be added to all of them? @onovotny?

**Comment by onovotny** [comment]
Only if you're using it yourself. Your dependencies should match what you have at build time.

**Comment by jamesmontemagno** [comment]
Hmmmm Well if the library is using it? Right now the nuspec just has it on the netstandard one?

**Comment by onovotny** [comment]
If the library is using it, then yes, it does need to be on all of the other groups too. Really the better answer to the manual group trimming is to get folks migrated off of packages.config :/

That and netstandard 2.0 help a lot.

**Comment by jamesmontemagno** [comment]
That makes sense, but we will need to upgrade all of our VS 2017 templates I would assume, and have an auto upgrade for existing projects?

**Comment by onovotny** [comment]
Might be better to have a discussion around what you're trying to and for what....happy to talk sometime Monday afternoon if you'd like.
