### ISSUE TITLE
U+00A0 (non-breaking space) is printable, but ColumnWidth returns -1 instead of 1

### ISSUE THREAD

**Issue by Pethical** [migueldeicaza/NStack#55]
Nbsp (160U) is printable character (space) , but Rune.ColumnWidth returns -1.

https://github.com/migueldeicaza/NStack/blob/8481cc1eb5b06c0e173d95351bcdd23b8235e54d/NStack/unicode/Rune.ColumnWidth.cs#L90-L91

I think we need this small change to fix it:
```cs
if (rune1 < 32U || rune1 >= (uint) sbyte.MaxValue && rune1 < 160U)
    return -1
```

Thanks, 
 Peter

**Comment by BDisp** [comment]
Thanks @Pethical. Can you please test your changes on the https://github.com/migueldeicaza/gui.cs, by running the `"CharacterMap.cs"` scenario from the `UICatalog`. Before you run, change the `MakePrintable` method from the `ConsoleDriver.cs`, to allow print the rune directly, by removing the substitute caracter. You will also need to checkout my PR #54 and add to the `Terminal.Gui` to use most recent changes to the `NStack`. Don't forget to remove the `NStack NuGet package`. The scroll view must be always aligned with a regular font, with no surpluses and no reductions in their width.

**Comment by Pethical** [comment]
I tested it. It's not working, the scrollbox is crazy (with the original, with the pr branch, and with my modification).

My original problem was with the `TableView` in gui.cs. I created a formatted integer column with right alignment.
The `N` format specifier with hungarian locale inserts `nbsp` as thousand separator. This counts -1 and the table cuts the last numbers, because the `TableView` calculates the string width as `Sum` of `Rune.ColumnWidth` for each character.

[TableView.cs - 533. line:](https://github.com/migueldeicaza/gui.cs/blob/64b00e3000f6a39302ded99334d8d5f5ef1ce2a1/Terminal.Gui/Views/TableView.cs#L533)
```cs
int toPad = availableHorizontalSpace - (representation.Sum (c => Rune.ColumnWidth (c)) + 1 /*leave 1 space for cell boundary*/);
```

### The original behavior:
![Bad](https://user-images.githubusercontent.com/10383468/141649015-b8d30395-099c-4c2c-a51f-4f4979892945.png)

### With the above modification:
![Good](https://user-images.githubusercontent.com/10383468/141649018-3f26b6af-113c-459b-a0e3-27761f127d8f.png)

**Comment by BDisp** [comment]
Thanks for your collaboration. I'll do the following change to my PR:

```cs
if (irune < 32 || (irune >= 0x7f && irune < 0xa0))
	return -1;
```

**Comment by Pethical** [comment]
Thank you :)
